name: CI/CD Pipeline

on:
  push:
    branches:
      - devel

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t davidjacovic/myapp-backend:latest ./backend
          docker push davidjacovic/myapp-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t davidjacovic/myapp-frontend:latest ./frontend
          docker push davidjacovic/myapp-frontend:latest

      - name: Send webhook to VM
        uses: actions/webhook@v1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
